// angular/src/app/shared/faq/faq-item/faq-item.ts
import { Component, input, signal } from '@angular/core';
import { FaIconComponent } from '@fortawesome/angular-fontawesome';
import { faChevronDown } from '@fortawesome/free-solid-svg-icons';
import { Faq as FaqEntry } from '../../../data/faq';

@Component({
  selector: 'app-faq-item',
  imports: [FaIconComponent],
  templateUrl: './faq-item.html',
  styleUrl: './faq-item.scss',
  host: { class: 'faq-item' },
})
export class FaqItem {
  readonly entry = input.required<FaqEntry>();

  protected readonly faChevronDown = faChevronDown;
  protected readonly expanded = signal(false);

  protected toggle(): void {
    this.expanded.update((value) => !value);
  }
}

// src/components/faq/FaqItem.tsx
import React from "react";
import {isMobile} from "react-device-detect";
import "./faq.scss"
import { useCollapse } from "react-collapsed";
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faChevronDown} from "@fortawesome/free-solid-svg-icons";

const FaqItem = (props: any) => {
  const { getCollapseProps, getToggleProps, isExpanded } = useCollapse();

  return <div className={`faq-item ${isMobile ? "mobile" : "desktop"}`}>
    <h5 {...getToggleProps()}><FontAwesomeIcon className={isExpanded ? "expanded" : "collapsed"} icon={faChevronDown} />{props.entry.question}</h5>
    <section {...getCollapseProps()}>{props.entry.answer}</section>
  </div>
}

export default FaqItem
