// src/components/menu/Menu.tsx
import "./menu.scss"
import React, { useEffect, useState, useRef } from 'react';
import Hamburger from 'hamburger-react'
import {isMobile} from "react-device-detect";
import {NavLink, useLocation} from "react-router";
// import {useClickAway} from "react-use";

const items= [
  { id: 1, label: 'Kezdőlap', href: '/' },
  { id: 3, label: 'Online programok', href: 'https://oktatas.kirillareka.hu/' },
  { id: 4, label: 'Egyéni kezelések', href: '/individual-treatments' },
  { id: 2, label: 'Kapcsolat', href: '/contacts' },
];

export const Menu = () => {
  const [isOpen, setIsOpen] = useState(false);
  const menuRef = useRef<any>(null);
  const hamburgerRef = useRef<any>(null);
  const location = useLocation();

  // const toggleMenu = () => {
  //   setIsOpen(!isOpen);
  // };

  useEffect(() => {
    setIsOpen(false);
  }, [location])

  // TODO handle click outside
  // useClickAway(menuRef, (event) => {
  //   if(hamburgerRef.current.children[0] !== event.target) setIsOpen(false);
  // });

  return (
    <div className={`menu ${isMobile ? 'mobile' : ''}`}>
      {isMobile && <span ref={hamburgerRef} role="button" aria-label="menu">
        <Hamburger rounded toggled={isOpen} toggle={setIsOpen} />
      </span>}

      <nav className={`menu-nav ${isMobile ? 'mobile' : ''} ${isOpen ? 'open' : ''}`}>
        <ul ref={menuRef} className={`menu-list ${isMobile ? 'mobile' : ''}`}>
          {items.map((item) => (
            <li key={item.id} role="menuitem">
              <NavLink to={item.href}>{item.label}</NavLink>
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
}

// angular/src/app/shared/menu/menu.ts
import { Component, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { NavigationEnd, Router, RouterLink, RouterLinkActive } from '@angular/router';
import { filter } from 'rxjs';

type MenuItem = {
  label: string;
  href: string;
  external?: boolean;
};

// Same items/order as the React Menu.tsx. "Online programok" links off-site to a separate
// learning platform, hence `external` (a plain <a>, not routerLink).
const ITEMS: MenuItem[] = [
  { label: 'Kezdőlap', href: '/' },
  { label: 'Online programok', href: 'https://oktatas.kirillareka.hu/', external: true },
  { label: 'Egyéni kezelések', href: '/individual-treatments' },
  { label: 'Kapcsolat', href: '/contacts' },
];

@Component({
  selector: 'app-menu',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './menu.html',
  styleUrl: './menu.scss',
})
export class Menu {
  private readonly router = inject(Router);

  protected readonly items = ITEMS;
  protected readonly isOpen = signal(false);

  constructor() {
    // Close the mobile dropdown whenever the route changes, mirroring the React Menu's
    // useEffect(() => setIsOpen(false), [location]).
    this.router.events
      .pipe(
        filter((event): event is NavigationEnd => event instanceof NavigationEnd),
        takeUntilDestroyed(),
      )
      .subscribe(() => this.isOpen.set(false));
  }

  protected toggle(): void {
    this.isOpen.update((open) => !open);
  }
}
