// src/components/social-contacts/Social.tsx
import "./social.scss"
import {FontAwesomeIcon} from "@fortawesome/react-fontawesome";
import {faFacebook, faInstagram, faTiktok, faYoutube} from "@fortawesome/free-brands-svg-icons";
import React from "react";

const Social = () => {
  return (
    <div className={"social"}>
      <label className="social-label">Vedd fel velem a kapcsolatot a közösségi média oldalaimon!</label>
      <div className="social-wrapper">
        <FontAwesomeIcon icon={faFacebook} />
        <FontAwesomeIcon icon={faInstagram} />
        <FontAwesomeIcon icon={faTiktok} />
        <FontAwesomeIcon icon={faYoutube} />
      </div>
    </div>
  );
};

export default Social;

// angular/src/app/shared/social/social.ts
import { Component } from '@angular/core';
import { FaIconComponent } from '@fortawesome/angular-fontawesome';
import { faFacebook, faInstagram, faTiktok, faYoutube } from '@fortawesome/free-brands-svg-icons';

@Component({
  selector: 'app-social',
  imports: [FaIconComponent],
  templateUrl: './social.html',
  styleUrl: './social.scss',
})
export class Social {
  protected readonly faFacebook = faFacebook;
  protected readonly faInstagram = faInstagram;
  protected readonly faTiktok = faTiktok;
  protected readonly faYoutube = faYoutube;
}
